### ISSUE TITLE
老哥 你qq多少？

### ISSUE THREAD

**Issue by 183883324** [hiero1225/Phoneix-logger#1]
我们现在有个需求 就是 如果移动端崩溃 就实时上传文件到服务器   或者有部分位置有调用问题我们自己打印 log  然后上传到服务器  请教下如果使用

**Comment by hiero1225** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Comment by hiero1225** [comment]
不好意思才看到，我qq 402341850




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "hiero1225/Phoneix-logger"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年11月30日(星期四) 下午4:07
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;[hiero1225/Phoneix-logger] 老哥 你qq多少？ (Issue #1)





 
我们现在有个需求 就是 如果移动端崩溃 就实时上传文件到服务器   或者有部分位置有调用问题我们自己打印 log  然后上传到服务器  请教下如果使用

**Comment by hiero1225** [comment]
源码中有基于jni的java层调用封装，是kotlin的，使用方法第一步就是初始化，第二步就是使用LoggerUtils.xx来调用即可
AppLogMgr.init(LoggerType.PHOENIX_LOG, app.filesDir.path,  app.filesDir.path,)
//日志最大容量为50M
AppLogMgr.MAX_FILE_SIZE = 5 * 1024 * 1024
LoggerUtils.i(HomeModule.MODULE_TAG, clzTag, "init with env: ${InfoUtils.getFormattedItemsInfo(app)}")
