### ISSUE TITLE
.dst文件里面的是buffer 字节内容吗，我当做流来解析是乱码，如何还原日志内容

### ISSUE THREAD

**Issue by JoeChency** [hiero1225/Phoneix-logger#2]

**Comment by hiero1225** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Comment by hiero1225** [comment]
是压缩过的格式，用zstd解压



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年9月30日(周一) 下午2:24
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: [hiero1225/Phoneix-logger] .dst文件里面的是流吗，我当做流来解析是乱码，如何还原日志内容 (Issue #2)
